services:
  db:
    container_name: lmc-db
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_PASSWORD=lmc
      - POSTGRES_USER=lmc
    volumes:
      - lmc-pg-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - lmc-network

  lmcapi:
    container_name: lmc-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - db
      - mailpit
      - redis
    volumes:
      - .:/lmcapi
      - /lmcapi/node_modules
    networks:
      - lmc-network

  mailpit:
    image: axllent/mailpit:v1.15
    ports:
      - '1025:1025' # SMTP server
      - '8025:8025' # Web interface
    restart: unless-stopped
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - lmc-network

  redis:
    image: redis:8.0.2-alpine
    container_name: lmc-redis
    ports:
      - "6379:6379"
    networks:
      - lmc-network
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - lmc-redis-data:/data

networks:
  lmc-network:
    driver: bridge

volumes:
  lmc-pg-data:
    driver: local
  lmc-redis-data:
    driver: local
